name: pocketark
description: Helper app for all things Lost Ark
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State
  inqvine_core_main: ^1.2.0
  inqvine_core_firebase: ^1.2.0
  firebase_core: ^1.13.1
  
  # UI

  # Other
  intl: ^0.17.0
  mocktail: ^0.3.0
  go_router: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.1.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/