name: pocketark
description: Helper app for all things Lost Ark
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State
  inqvine_core_main: ^1.2.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  
  # UI
  go_router: ^3.0.4
  flutter_spinkit: ^5.1.0

  # Other
  intl: ^0.17.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0
  build_runner: ^2.1.8

  # UI
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_native_splash:
  color: "2A303C"
  ios: false
  android: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/logo_flat.png"
  image_path_ios: "assets/images/logo.png"
  adaptive_icon_background: "#FF2A303C"
  adaptive_icon_foreground: "assets/images/logo_flat.png"