name: events
description: Helper tool for uploading events
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  firebase: ^9.0.2
  protobuf: ^2.0.1

dev_dependencies: